apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "designate-certmanager-webhook.fullname" . }}-apiservice
  labels:
    app: {{ include "designate-certmanager-webhook.name" . }}
    chart: {{ include "designate-certmanager-webhook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  apiservice.yaml: |
    apiVersion: apiregistration.k8s.io/v1
    kind: APIService
    metadata:
      name: v1alpha1.acme.syseleven.de
      labels:
        app: {{ include "designate-certmanager-webhook.name" . }}
        chart: {{ include "designate-certmanager-webhook.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ include "designate-certmanager-webhook.servingCertificate" . }}"
    spec:
      group: acme.syseleven.de
      groupPriorityMinimum: 1000
      versionPriority: 15
      service:
        name: {{ include "designate-certmanager-webhook.fullname" . }}
        namespace: {{ .Release.Namespace }}
      version: v1alpha1
