replicaCount: 1

certManager:
  namespace: ~
  serviceAccountName: cert-manager

image:
  repository: syseleven/designate-certmanager-webhook
  tag: 0.2.12
  pullPolicy: IfNotPresent
  alpine:
    repository: alpine
    tag: latest
  kubectl:
    repository: bitnami/kubectl
    tag: latest

imagePullSecrets: []

# This secret holds the authenitcation information for designate
credentialsSecret: cloud-credentials

# If you fill out these information the helm chart will use your provided
# information and overwrite an existing ${credentialsSecret} secret. If the values
# are kept empty, you must create a secret with desired values manually. Please
# refer to the README for more information. You may use either the application credentials.
# Or the username and password combination to authenticate.
# The username and password also require a projectid or name. Do not set the projectid if you are using application credentials.
openstack:
  region_name: ""
  auth_url: ""
  domain_name: ""
  application_credential_name: ""
  application_credential_id: ""
  application_credential_secret: ""
#  username: ""
#  password: ""
#  project_id: ""
#  project_name: "" # Use project_id OR project_name

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
