replicaCount: 1

certManager:
  namespace: ~
  serviceAccountName: cert-manager

image:
  repository: syseleven/designate-certmanager-webhook
  tag: 0.2.18
  pullPolicy: IfNotPresent

alpine:
  image:
    repository: alpine
    tag: latest
kubectl:
  image:
    repository: bitnami/kubectl
    tag: latest

imagePullSecrets: []

# This secret holds the authenitcation information for designate
credentialsSecret: cloud-credentials

# If you fill out these information the helm chart will use your provided
# information and overwrite an existing ${credentialsSecret} secret. If the values
# are kept empty, you must create a secret with desired values manually. Please
# refer to the README for more information.
openstack:
  username: ""
  password: ""
  application_credential_id: ""
  application_credential_secret: ""
  project_id: ""
  project_name: "" # Use project_id OR project_name
  region_name: ""
  auth_url: ""
  domain_name: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 443

podSecurityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

probes:
  startupProbe:
    httpGet:
      scheme: HTTPS
      path: /healthz
      port: https
  
  livenessProbe:
    httpGet:
      scheme: HTTPS
      path: /healthz
      port: https

  readinessProbe:
    httpGet:
      scheme: HTTPS
      path: /healthz
      port: https
