name: PR Integration Test

on:
  workflow_run:
    workflows: [ "Test Workflow" ]
    types: [ completed ]

jobs:
  integration-test:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    environment: openstack-integration

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ github.event.workflow_run.head_sha }}

    - name: Run test
      env:
        TEST_ZONE_NAME: ${{ vars.TEST_ZONE_NAME }}
        OS_APPLICATION_CREDENTIAL_ID: ${{ secrets.OS_APPLICATION_CREDENTIAL_ID }}
        OS_APPLICATION_CREDENTIAL_SECRET: ${{ secrets.OS_APPLICATION_CREDENTIAL_SECRET }}
        OS_AUTH_TYPE: ${{ vars.OS_AUTH_TYPE }}
        OS_AUTH_URL: ${{ vars.OS_AUTH_URL }}
        OS_ENDPOINT_TYPE: ${{ vars.OS_ENDPOINT_TYPE }}
        OS_IDENTITY_API_VERSION: ${{ vars.OS_IDENTITY_API_VERSION }}
        OS_INTERFACE: ${{ vars.OS_INTERFACE }}
        OS_PROJECT_DOMAIN_NAME: ${{ vars.OS_PROJECT_DOMAIN_NAME }}
        OS_REGION_NAME: ${{ vars.OS_REGION_NAME }}
        OS_USER_DOMAIN_NAME: ${{ vars.OS_USER_DOMAIN_NAME }}
      run: make test
